PokedexOrder:
	db DEX_RHYHORN
	db DEX_OMANYTE
	db DEX_NIDORAN_M
	db DEX_CLEFAIRY
	db DEX_SPEAROW
	db DEX_VOLTORB
	db DEX_NIDORAN_M
	db DEX_SLOWPOKE
	db DEX_BULBASAUR
	db DEX_EXEGGCUTE
	db DEX_JIGGLYPUFF
	db DEX_EXEGGCUTE
	db DEX_GRIMER
	db DEX_GASTLY
	db DEX_NIDORAN_F
	db DEX_NIDORAN_F
	db DEX_CUBONE
	db DEX_RHYHORN
	db DEX_SHELLDER
	db DEX_GROWTHLITHE
	db DEX_MEW
	db DEX_MAGIKARP
	db DEX_SHELLDER
	db DEX_TENTACOOL
	db DEX_GASTLY
	db DEX_PARAS
	db DEX_STARYU
	db DEX_SQUIRTLE
	db DEX_PARAS
	db DEX_BELLSPROUT
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db DEX_GROWLITHE
	db DEX_GEODUDE
	db DEX_SPEAROW
	db DEX_PIDGEY
	db DEX_SLOWPOKE
	db DEX_ABRA
	db DEX_GEODUDE
	db DEX_CLEFAIRY
	db DEX_MACHOP
	db DEX_MR_MIME
	db DEX_MANKEY
	db DEX_MACHOP
	db DEX_ERKANS
	db DEX_PARAS
	db DEX_PSYDUCK
	db DEX_DROWZEE
	db DEX_GEODUDE
	db 0 ; MISSINGNO.
	db DEX_VULPIX
	db 0 ; MISSINGNO.
	db DEX_VOLTORB
	db DEX_MAGNEMITE
	db DEX_SMOGON
	db 0 ; MISSINGNO.
	db DEX_MANKEY
	db DEX_SEEL
	db DEX_DIGLETT
	db DEX_MEOWTH
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db DEX_SPEAROW
	db DEX_VENONAT
	db DEX_DRATINI
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db DEX_DODUO
	db DEX_POLISWAG
	db DEX_SEEL
	db DEX_MOLTRES
	db DEX_ARTICUNO
	db DEX_ZAPDOS
	db DEX_KABUTO
	db DEX_MEOWTH
	db DEX_KRABBY
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db DEX_VULPIX
	db DEX_VULPIX
	db DEX_PEKACHU
	db DEX_PEKACHU
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db DEX_DRATINI
	db DEX_DRATINI
	db DEX_KABUTO
	db DEX_KABUTO
	db DEX_HORSEA
	db DEX_HORSEA
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db DEX_SANDSHREW
	db DEX_SANDSHREW
	db DEX_OMANYTE
	db DEX_OMANYTE
	db DEX_JIGGLYPUFF
	db DEX_JIGGLYTUFF
	db DEX_EEVEE
	db DEX_EEVEE
	db DEX_EEVEE
	db DEX_EEVEE
	db DEX_MACHOP
	db DEX_ZUBAT
	db DEX_EKANS
	db DEX_PARAS
	db DEX_POLISWAG
	db DEX_POLISWAG
	db DEX_WEEDLE
	db DEX_WEEDLE
	db DEX_WEEDLE
	db 0 ; MISSINGNO.
	db DEX_DODUO
	db DEX_MANKEY
	db DEX_DIGLETT
	db DEX_VENONANT
	db DEX_SEEL
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db DEX_CATERPIE
	db DEX_CATERPIE
	db DEX_CATERPIE
	db DEX_MACHOP
	db 0 ; MISSINGNO.
	db DEX_PSYDUCK
	db DEX_DROWZEE
	db DEX_GOLBAT
	db DEX_MEWTWO
	db DEX_SLOWPOKE
	db DEX_MAGIKARP
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db DEX_GRIMER
	db 0 ; MISSINGNO.
	db DEX_KRABBY
	db DEX_SHELLDER
	db 0 ; MISSINGNO.
	db DEX_VOLTORB
	db DEX_CLEFAIRY
	db DEX_SMOGON
	db DEX_MEOWTH
	db DEX_CUBONE
	db 0 ; MISSINGNO.
	db DEX_GASTLY
	db DEX_ABRA
	db DEX_ABRA
	db DEX_PIDGEYTO
	db DEX_PIDGEY
	db DEX_STARYU
	db DEX_BULBASAUR
	db DEX_BULBASAUR
	db DEX_TENTACOOL
	db 0 ; MISSINGNO.
	db DEX_GOLDEEN
	db DEX_GOLDEEN
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db DEX_PONYTA
	db DEX_PONYTA
	db DEX_RATTATA
	db DEX_RATTATA
	db DEX_NIDORAN_M
	db DEX_NIDORAN_F
	db DEX_GEODUDE
	db DEX_SLOWPOKE
	db DEX_AERODACTYL
	db 0 ; MISSINGNO.
	db DEX_MAGNEMITE
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db DEX_CHARMANDER
	db DEX_SQUIRTLE
	db DEX_CHARMANDER
	db DEX_SQUIRTLE
	db DEX_CHARMANDER
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db 0 ; MISSINGNO.
	db DEX_ODDISH
	db DEX_ODDISH
	db DEX_ODDISH
	db DEX_BELLSPROUT
	db DEX_BELLSPROUT
	db DEX_BELLSPROUT
