TrainerDataPointers:
	dw YoungsterData
	dw BugCatcherData
	dw LassData
	dw SailorData
	dw JrTrainerMData
	dw JrTrainerFData
	dw PokemaniacData
	dw SuperNerdData
	dw HikerData
	dw BikerData
	dw BurglarData
	dw EngineerData
	dw Juggler1Data
	dw FisherData
	dw SwimmerData
	dw CueBallData
	dw GamblerData
	dw BeautyData
	dw PsychicData
	dw RockerData
	dw JugglerData
	dw TamerData
	dw BirdKeeperData
	dw BlackbeltData
	dw Green1Data
	dw ProfOakData
	dw ChiefData
	dw ScientistData
	dw GiovanniData
	dw RocketData
	dw CooltrainerMData
	dw CooltrainerFData
	dw BrunoData
	dw BrockData
	dw MistyData
	dw LtSurgeData
	dw ErikaData
	dw KogaData
	dw BlaineData
	dw SabrinaData
	dw GentlemanData
	dw Green2Data
	dw Green3Data
	dw LoreleiData
	dw ChannelerData
	dw AgathaData
	dw LanceData

; if first byte != FF, then
	; first byte is level (of all pokemon on this team)
	; all the next bytes are pokemon species
	; null-terminated
; if first byte == FF, then
	; first byte is FF (obviously)
	; every next two bytes are a level and species
	; null-terminated

YoungsterData:
; Route 3
	db 5,RATTATA,EKANS,0
	db 5,SPEAROW,0
; Mt. Moon 1F
	db 5,RATTATA,RATTATA,ZUBAT,0
; Route 24
	db 5,RATTATA,EKANS,ZUBAT,0
; Route 25
	db 5,RATTATA,SPEAROW,0
	db 5,SLOWPOKE,0
	db 5,EKANS,SANDSHREW,0
; SS Anne 1F Rooms
	db 5,NIDORAN_M,0
; Route 11
	db 5,EKANS,0
	db 5,SANDSHREW,ZUBAT,0
	db 5,RATTATA,RATTATA,RATTATA,0
	db 5,NIDORAN_M,NIDORAN_M,0
; Unused
	db 5,SPEAROW,RATTATA,RATTATA,SPEAROW,0
BugCatcherData:
; Viridian Forest
	db 5,WEEDLE,CATERPIE,0
	db 5,WEEDLE,WEEDLE,WEEDLE,0
	db 5,WEEDLE,0
; Route 3
	db 5,CATERPIE,WEEDLE,CATERPIE,0
	db 5,WEEDLE,WEEDLE,CATERPIE,CATERPIE,0
	db 5,CATERPIE,CATERPIE,0
; Mt. Moon 1F
	db 5,WEEDLE,WEEDLE,0
	db 5,CATERPIE,CATERPIE,CATERPIE,0
; Route 24
	db 5,CATERPIE,WEEDLE,0
; Route 6
	db 5,WEEDLE,CATERPIE,WEEDLE,0
	db 5,CATERPIE,0
; Unused
	db 5,CATERPIE,CATERPIE,VENONAT,0
; Route 9
	db 5,WEEDLE,WEEDLE,0
	db 5,CATERPIE,WEEDLE,VENONAT,0
LassData:
; Route 3
	db 5,PIDGEY,PIDGEY,0
	db 5,RATTATA,NIDORAN_M,0
	db 5,JIGGLYPUFF,0
; Route 4
	db 5,PARAS,PARAS,PARAS,0
; Mt. Moon 1F
	db 5,ODDISH,BELLSPROUT,0
	db 5,CLEFAIRY,0
; Route 24
	db 5,PIDGEY,NIDORAN_F,0
	db 5,PIDGEY,NIDORAN_F,0
; Route 25
	db 5,NIDORAN_M,NIDORAN_F,0
	db 5,ODDISH,PIDGEY,ODDISH,0
; SS Anne 1F Rooms
	db 5,PIDGEY,NIDORAN_F,0
; SS Anne 2F Rooms
	db 5,RATTATA,PEKACHU,0
; Route 8
	db 5,NIDORAN_F,NIDORAN_F,0
	db 5,MEOWTH,MEOWTH,MEOWTH,0
	db 5,PIDGEY,RATTATA,NIDORAN_M,MEOWTH,PEKACHU,0
	db 5,CLEFAIRY,CLEFAIRY,0
; Celadon Gym
	db 5,BELLSPROUT,BELLSPROUT,0
	db 5,ODDISH,ODDISH,0
SailorData:
; SS Anne Stern
	db 5,MACHOP,SHELLDER,0
	db 5,MACHOP,TENTACOOL,0
; SS Anne B1F Rooms
	db 5,SHELLDER,0
	db 5,HORSEA,SHELLDER,TENTACOOL,0
	db 5,TENTACOOL,STARYU,0
	db 5,HORSEA,HORSEA,HORSEA,0
	db 5,MACHOP,0
; Vermilion Gym
	db 5,PEKACHU,PEKACHU,0
JrTrainerMData:
; Pewter Gym
	db 5,DIGLETT,SANDSHREW,0
; Route 24/Route 25
	db 5,RATTATA,EKANS,0
; Route 24
	db 5,MANKEY,0
; Route 6
	db 5,SQUIRTLE,0
	db 5,SPEAROW,RATTATA,0
; Unused
	db 5,DIGLETT,DIGLETT,SANDSHREW,0
; Route 9
	db 5,GROWLITHE,CHARMANDER,0
	db 5,RATTATA,DIGLETT,EKANS,SANDSHREW,0
; Route 12
	db 5,NIDORAN_M,NIDORAN_M,0
JrTrainerFData:
; Cerulean Gym
	db 5,GOLDEEN,0
; Route 6
	db 5,RATTATA,PEKACHU,0
	db 5,PIDGEY,PIDGEY,PIDGEY,0
; Unused
	db 5,BULBASAUR,0
; Route 9
	db 5,ODDISH,BELLSPROUT,ODDISH,BELLSPROUT,0
	db 5,MEOWTH,0
; Route 10
	db 5,PEKACHU,CLEFAIRY,0
	db 5,PIDGEY,PIDGEY,0
; Rock Tunnel B1F
	db 5,JIGGLYPUFF,PIDGEY,MEOWTH,0
	db 5,ODDISH,BULBASAUR,0
; Celadon Gym
	db 5,BULBASAUR,BULBASAUR,0
; Route 13
	db 5,PIDGEY,MEOWTH,RATTATA,PEKACHU,MEOWTH,0
	db 5,POLISWAG,POLISWAG,0
	db 5,PIDGEY,MEOWTH,PIDGEY,PIDGEY,0
	db 5,GOLDEEN,POLISWAG,HORSEA,0
; Route 20
	db 5,GOLDEEN,GOLDEEN,0
; Rock Tunnel 1F
	db 5,BELLSPROUT,CLEFAIRY,0
	db 5,MEOWTH,ODDISH,PIDGEY,0
	db 5,PIDGEY,RATTATA,RATTATA,BELLSPROUT,0
; Route 15
	db 5,ODDISH,ODDISH,ODDISH,0
	db 5,PEKACHU,PEKACHU,0
	db 5,CLEFAIRY,0
	db 5,BELLSPROUT,ODDISH,BELLSPROUT,0
; Route 20
	db 5,TENTACOOL,HORSEA,SEEL,0
PokemaniacData:
; Route 10
	db 5,RHYHORN,OMANYTE,0
	db 5,CUBONE,SLOWPOKE,0
; Rock Tunnel B1F
	db 5,SLOWPOKE,SLOWPOKE,SLOWPOKE,0
	db 5,CHARMANDER,CUBONE,0
	db 5,SLOWPOKE,0
; Victory Road 2F
	db 5,CHARMANDER,SHELLDER,OMANYTE,0
; Rock Tunnel 1F
	db 5,CUBONE,SLOWPOKE,0
SuperNerdData:
; Mt. Moon 1F
	db 5,MAGNEMITE,VOLTORB,0
; Mt. Moon B2F
	db 5,GRIMER,VOLTORB,SMOGON,0
; Route 8
	db 5,VOLTORB,SMOGON,VOLTORB,MAGNEMITE,0
	db 5,GRIMER,GRIMER,GRIMER,0
	db 5,SMOGON,0
; Unused
	db 5,SMOGON,MAGNEMITE,SMOGON,0
	db 5,MAGNEMITE,MAGNEMITE,SMOGON,MAGNEMITE,0
	db 5,MAGNEMITE,VOLTORB,0
; Cinnabar Gym
	db 5,VULPIX,VULPIX,VULPIX,0
	db 5,PONYTA,CHARMANDER,VULPIX,GROWLITHE,0
	db 5,PONYTA,0
	db 5,GROWLITHE,VULPIX,0
HikerData:
; Mt. Moon 1F
	db 5,GEODUDE,GEODUDE,RHYHORN,0
; Route 25
	db 5,MACHOP,GEODUDE,0
	db 5,GEODUDE,GEODUDE,MACHOP,GEODUDE,0
	db 5,RHYHORN,0
; Route 9
	db 5,GEODUDE,RHYHORN,0
	db 5,GEODUDE,MACHOP,GEODUDE,0
; Route 10
	db 5,GEODUDE,RHYHORN,0
	db 5,RHYHORN,GEODUDE,0
; Rock Tunnel B1F
	db 5,GEODUDE,GEODUDE,GEODUDE,0
	db 5,GEODUDE,0
; Route 9/Rock Tunnel B1F
	db 5,MACHOP,RHYHORN,0
; Rock Tunnel 1F
	db 5,GEODUDE,MACHOP,GEODUDE,GEODUDE,0
	db 5,RHYHORN,RHYHORN,GEODUDE,0
	db 5,GEODUDE,GEODUDE,0
BikerData:
; Route 13
	db 5,SMOGON,SMOGON,SMOGON,0
; Route 14
	db 5,SMOGON,GRIMER,0
; Route 15
	db 5,SMOGON,SMOGON,SMOGON,SMOGON,GRIMER,0
	db 5,SMOGON,GRIMER,SMOGON,0
; Route 16
	db 5,GRIMER,SMOGON,0
	db 5,SMOGON,0
	db 5,GRIMER,GRIMER,GRIMER,GRIMER,0
; Route 17
	; From https://www.smogon.com/smog/issue27/glitch:
	; 0E:5FC2 is offset of the ending 0 for this first Biker on Route 17.
	; BaseStats + (MonBaseStatsEnd - MonBaseStats) * (000 - 1) = $5FC2;
	; that's the formula from GetMonHeader for the base stats of mon #000.
	; (BaseStats = $43DE and BANK(BaseStats) = $0E.)
	; Finally, PokedexOrder lists 0 as the dex ID for every MissingNo.
	; The result is that this data gets interpreted as the base stats
	; for MissingNo: 0,5,GRIMER,0,5,VOLTORB,VOLTORB,0,...,5,GRIMER,GRIMER.
	db 5,SMOGON,SMOGON,SMOGON,0
	db 5,GRIMER,0
	db 5,VOLTORB,VOLTORB,0
	db 5,SMOGON,GRIMER,0
	db 5,SMOGON,SMOGON,SMOGON,SMOGON,SMOGON,0
; Route 14
	db 5,SMOGON,SMOGON,GRIMER,SMOGON,0
	db 5,GRIMER,GRIMER,SMOGON,0
	db 5,SMOGON,GRIMER,0
BurglarData:
; Unused
	db 5,GROWLITHE,VULPIX,0
	db 5,GROWLITHE,0
	db 5,VULPIX,CHARMANDER,PONYTA,0
; Cinnabar Gym
	db 5,GROWLITHE,VULPIX,VULPIX,0
	db 5,PONYTA,0
	db 5,VULPIX,GROWLITHE,0
; Mansion 2F
	db 5,CHARMANDER,CHARMANDER,0
; Mansion 3F
	db 5,VULPIX,0
; Mansion B1F
	db 5,GROWLITHE,PONYTA,0
EngineerData:
; Unused
	db 5,VOLTORB,MAGNEMITE,0
; Route 11
	db 5,MAGNEMITE,0
	db 5,MAGNEMITE,MAGNEMITE,MAGNEMITE,0
Juggler1Data:
; none
FisherData:
; SS Anne 2F Rooms
	db 5,GOLDEEN,TENTACOOL,GOLDEEN,0
; SS Anne B1F Rooms
	db 5,TENTACOOL,STARYU,SHELLDER,0
; Route 12
	db 5,GOLDEEN,POLISWAG,GOLDEEN,0
	db 5,TENTACOOL,GOLDEEN,0
	db 5,GOLDEEN,0
	db 5,POLISWAG,SHELLDER,GOLDEEN,HORSEA,0
; Route 21
	db 5,GOLDEEN,GOLDEEN,GOLDEEN,GOLDEEN,0
	db 5,SHELLDER,SHELLDER,0
	db 5,MAGIKARP,MAGIKARP,MAGIKARP,MAGIKARP,MAGIKARP,MAGIKARP,0
	db 5,GOLDEEN,GOLDEEN,0
; Route 12
	db 5,MAGIKARP,MAGIKARP,0
SwimmerData:
; Cerulean Gym
	db 5,HORSEA,SHELLDER,0
; Route 19
	db 5,TENTACOOL,SHELLDER,0
	db 5,GOLDEEN,HORSEA,STARYU,0
	db 5,POLISWAG,POLISWAG,0
	db 5,HORSEA,TENTACOOL,TENTACOOL,GOLDEEN,0
	db 5,GOLDEEN,SHELLDER,GOLDEEN,0
	db 5,HORSEA,HORSEA,0
	db 5,TENTACOOL,TENTACOOL,STARYU,HORSEA,TENTACOOL,0
; Route 20
	db 5,SHELLDER,SHELLDER,0
	db 5,STARYU,0
	db 5,HORSEA,HORSEA,HORSEA,HORSEA,0
; Route 21
	db 5,HORSEA,TENTACOOL,0
	db 5,STARYU,0
	db 5,STARYU,SQUIRTLE,0
	db 5,POLISWAG,TENTACOOL,HORSEA,0
CueBallData:
; Route 16
	db 5,MACHOP,MANKEY,MACHOP,0
	db 5,MANKEY,MACHOP,0
	db 5,MACHOP,0
; Route 17
	db 5,MANKEY,MANKEY,0
	db 5,MACHOP,MACHOP,0
	db 5,MACHOP,0
	db 5,MANKEY,MANKEY,MACHOP,MACHOP,0
	db 5,MANKEY,MACHOP,0
; Route 21
	db 5,TENTACOOL,TENTACOOL,TENTACOOL,0
GamblerData:
; Route 11
	db 5,POLISWAG,HORSEA,0
	db 5,BELLSPROUT,ODDISH,0
	db 5,VOLTORB,MAGNEMITE,0
	db 5,GROWLITHE,VULPIX,0
; Route 8
	db 5,POLISWAG,POLISWAG,POLISWAG,0
; Unused
	db 5,RHYHORN,GEODUDE,GEODUDE,0
; Route 8
	db 5,GROWLITHE,VULPIX,0
BeautyData:
; Celadon Gym
	db 5,ODDISH,BELLSPROUT,ODDISH,BELLSPROUT,0
	db 5,BELLSPROUT,BELLSPROUT,0
	db 5,EXEGGCUTE,0
; Route 13
	db 5,RATTATA,PEKACHU,RATTATA,0
	db 5,CLEFAIRY,MEOWTH,0
; Route 20
	db 5,GOLDEEN,0
	db 5,SHELLDER,SHELLDER,SHELLDER,0
	db 5,POLISWAG,GOLDEEN,0
; Route 15
	db 5,PIDGEY,JIGGLYTUFF,0
	db 5,BULBASAUR,BULBASAUR,0
; Unused
	db 5,BELLSPROUT,BELLSPROUT,BELLSPROUT,0
; Route 19
	db 5,POLISWAG,GOLDEEN,GOLDEEN,GOLDEEN,POLISWAG,0
	db 5,GOLDEEN,GOLDEEN,0
	db 5,STARYU,STARYU,STARYU,0
; Route 20
	db 5,HORSEA,HORSEA,HORSEA,0
PsychicData:
; Saffron Gym
	db 5,ABRA,SLOWPOKE,MR_MIME,ABRA,0
	db 5,MR_MIME,ABRA,0
	db 5,SLOWPOKE,SLOWPOKE,SLOWPOKE,0
	db 5,SLOWPOKE,0
RockerData:
; Vermilion Gym
	db 5,VOLTORB,MAGNEMITE,VOLTORB,0
; Route 12
	db 5,VOLTORB,VOLTORB,0
JugglerData:
; Silph Co. 5F
	db 5,ABRA,MR_MIME,0
; Victory Road 2F
	db 5,DROWZEE,DROWZEE,ABRA,ABRA,0
; Fuchsia Gym
	db 5,DROWZEE,DROWZEE,ABRA,DROWZEE,0
	db 5,DROWZEE,DROWZEE,0
; Victory Road 2F
	db 5,MR_MIME,0
; Unused
	db 5,DROWZEE,0
; Fuchsia Gym
	db 5,DROWZEE,0
	db 5,DROWZEE,ABRA,0
TamerData:
; Fuchsia Gym
	db 5,SANDSHREW,ERKANS,0
	db 5,ERKANS,SANDSHREW,ERKANS,0
; Viridian Gym
	db 5,RHYHORN,0
	db 5,ERKANS,MEOWTH,0
; Victory Road 2F
	db 5,MEOWTH,PSYDUCK,0
; Unused
	db 5,RHYHORN,MANKEY,ERKANS,MEOWTH,0
BirdKeeperData:
; Route 13
	db 5,PIDGEY,PIDGEY,0
	db 5,SPEAROW,PIDGEY,PIDGEY,SPEAROW,SPEAROW,0
	db 5,PIDGEY,PIDGEY,SPEAROW,SPEAROW,0
; Route 14
	db 5,SPEAROW,0
	db 5,SPEAROW,SPEAROW,0
; Route 15
	db 5,PIDGEY,SPEAROW,DODUO,PIDGEY,0
	db 5,DODUO,DODUO,DODUO,0
; Route 18
	db 5,SPEAROW,SPEAROW,0
	db 5,DODUO,0
	db 5,SPEAROW,SPEAROW,SPEAROW,SPEAROW,0
; Route 20
	db 5,SPEAROW,SPEAROW,PIDGEY,0
; Unused
	db 5,PIDGEY,PIDGEY,PIDGEY,PIDGEY,0
	db 5,SPEAROW,SPEAROW,0
; Route 14
	db 5,PIDGEY,DODUO,PIDGEY,0
	db 5,PIDGEY,SPEAROW,PIDGEY,SPEAROW,0
	db 5,PIDGEY,SPEAROW,0
	db 5,SPEAROW,DODUO,SPEAROW,0
BlackbeltData:
; Fighting Dojo
	db 5,MANKEY,MANKEY,0
	db 5,MANKEY,MANKEY,MANKEY,0
	db 5,MACHOP,MACHOP,0
	db 5,MANKEY,0
	db 5,MACHOP,MANKEY,MANKEY,0
; Viridian Gym
	db 5,MACHOP,MACHOP,0
	db 5,MACHOP,0
	db 5,MACHOP,MACHOP,MACHOP,0
; Victory Road 2F
	db 5,MACHOP,MACHOP,MACHOP,0
Green1Data:
	db 5,SQUIRTLE,0
	db 5,BULBASAUR,0
	db 5,CHARMANDER,0
; Route 22
	db $FF,5,PIDGEY,5,SQUIRTLE,0
	db $FF,5,PIDGEY,5,BULBASAUR,0
	db $FF,5,PIDGEY,5,CHARMANDER,0
; Cerulean City
	db $FF,5,PIDGEY,5,ABRA,5,RATTATA,5,SQUIRTLE,0
	db $FF,5,PIDGEY,5,ABRA,5,RATTATA,5,BULBASAUR,0
	db $FF,5,PIDGEY,5,ABRA,5,RATTATA,5,CHARMANDER,0
ProfOakData:
; Unused
	db $FF,5,MEOWTH,5,EXEGGCUTE,5,GROWLITHE,5,SQUIRTLE,5,TENTACOOL,0
	db $FF,5,MEOWTH,5,EXEGGCUTE,5,GROWLITHE,5,BULBASAUR,5,TENTACOOL,0
	db $FF,5,MEOWTH,5,EXEGGCUTE,5,GROWLITHE,5,CHARMANDER,5,TENTACOOL,0
ChiefData:
; none
ScientistData:
; Unused
	db 5,SMOGON,VOLTORB,0
; Silph Co. 2F
	db 5,GRIMER,SMOGON,SMOGON,SMOGON,0
	db 5,MAGNEMITE,VOLTORB,MAGNEMITE,0
; Silph Co. 3F/Mansion 1F
	db 5,VOLTORB,SMOGON,0
; Silph Co. 4F
	db 5,VOLTORB,0
; Silph Co. 5F
	db 5,MAGNEMITE,SMOGON,SMOGON,MAGNEMITE,0
; Silph Co. 6F
	db 5,VOLTORB,SMOGON,MAGNEMITE,MAGNEMITE,SMOGON,0
; Silph Co. 7F
	db 5,VOLTORB,GRIMER,0
; Silph Co. 8F
	db 5,GRIMER,VOLTORB,0
; Silph Co. 9F
	db 5,VOLTORB,SMOGON,MAGNEMITE,0
; Silph Co. 10F
	db 5,MAGNEMITE,SMOGON,0
; Mansion 3F
	db 5,MAGNEMITE,MAGNEMITE,VOLTORB,0
; Mansion B1F
	db 5,MAGNEMITE,VOLTORB,0
GiovanniData:
; Rocket Hideout B4F
	db $FF,5,RHYHORN,5,RHYHORN,5,OMANYTE,0
; Silph Co. 11F
	db $FF,5,NIDORAN_M,5,OMANYTE,5,RHYHORN,5,NIDORAN_F,0
; Viridian Gym
	db $FF,5,RHYHORN,5,DIGLETT,5,NIDORAN_F,5,NIDORAN_M,5,RHYHORN,0
RocketData:
; Mt. Moon B2F
	db 5,RATTATA,ZUBAT,0
	db 5,SANDSHREW,RATTATA,ZUBAT,0
	db 5,ZUBAT,EKANS,0
	db 5,RATTATA,0
; Cerulean City
	db 5,MACHOP,DROWZEE,0
; Route 24
	db 5,EKANS,ZUBAT,0
; Game Corner
	db 5,RATTATA,ZUBAT,0
; Rocket Hideout B1F
	db 5,DROWZEE,MACHOP,0
	db 5,RATTATA,RATTATA,0
	db 5,GRIMER,SMOGON,SMOGON,0
	db 5,RATTATA,RATTATA,RATTATA,RATTATA,0
	db 5,GRIMER,SMOGON,0
; Rocket Hideout B2F
	db 5,ZUBAT,SMOGON,GRIMER,ZUBAT,RATTATA,0
; Rocket Hideout B3F
	db 5,RATTATA,RATTATA,DROWZEE,0
	db 5,MACHOP,MACHOP,0
; Rocket Hideout B4F
	db 5,SANDSHREW,EKANS,SANDSHREW,0
	db 5,EKANS,SANDSHREW,ERKANS,0
	db 5,SMOGON,ZUBAT,0
; Pokémon Tower 7F
	db 5,ZUBAT,ZUBAT,ZUBAT,0
	db 5,SMOGON,DROWZEE,0
	db 5,ZUBAT,RATTATA,RATTATA,ZUBAT,0
; Unused
	db 5,DROWZEE,SMOGON,0
; Silph Co. 2F
	db 5,CUBONE,ZUBAT,0
	db 5,ZUBAT,ZUBAT,ZUBAT,RATTATA,ZUBAT,0
; Silph Co. 3F
	db 5,RATTATA,DROWZEE,RATTATA,0
; Silph Co. 4F
	db 5,MACHOP,DROWZEE,0
	db 5,EKANS,ZUBAT,CUBONE,0
; Silph Co. 5F
	db 5,ERKANS,0
	db 5,DROWZEE,0
; Silph Co. 6F
	db 5,MACHOP,MACHOP,0
	db 5,ZUBAT,ZUBAT,ZUBAT,0
; Silph Co. 7F
	db 5,RATTATA,ERKANS,SMOGON,ZUBAT,0
	db 5,CUBONE,CUBONE,0
	db 5,SANDSHREW,SANDSHREW,0
; Silph Co. 8F
	db 5,RATTATA,ZUBAT,ZUBAT,RATTATA,0
	db 5,SMOGON,ZUBAT,SMOGON,0
; Silph Co. 9F
	db 5,DROWZEE,GRIMER,MACHOP,0
	db 5,ZUBAT,DROWZEE,DROWZEE,0
; Silph Co. 10F
	db 5,MACHOP,0
; Silph Co. 11F
	db 5,RATTATA,RATTATA,ZUBAT,RATTATA,EKANS,0
	db 5,CUBONE,DROWZEE,CUBONE,0
CooltrainerMData:
; Viridian Gym
	db 5,NIDORAN_M,NIDORAN_M,0
; Victory Road 3F
	db 5,EXEGGCUTE,SHELLDER,GROWLITHE,0
	db 5,KRABBY,TENTACOOL,SQUIRTLE,0
; Unused
	db 5,KRABBY,STARYU,0
; Victory Road 1F
	db 5,BULBASAUR,SQUIRTLE,CHARMANDER,CHARMANDER,0
; Unused
	db 5,BULBASAUR,SQUIRTLE,CHARMANDER,0
	db 5,NIDORAN_M,0
	db 5,KRABBY,SHELLDER,0
; Viridian Gym
	db 5,SANDSHREW,DIGLETT,0
	db 5,RHYHORN,0
CooltrainerFData:
; Celadon Gym
	db 5,BELLSPROUT,ODDISH,BULBASAUR,0
; Victory Road 3F
	db 5,BELLSPROUT,BELLSPROUT,BELLSPROUT,0
	db 5,PARAS,SEEL,CLEFAIRY,0
; Unused
	db 5,ODDISH,CATERPIE,0
; Victory Road 1F
	db 5,MEOWTH,VULPIX,0
; Unused
	db 5,BULBASAUR,BULBASAUR,0
	db 5,NIDORAN_F,NIDORAN_F,0
	db 5,MEOWTH,VULPIX,PEKACHU,0
BrunoData:
	db $FF,5,RHYHORN,5,MANKEY,5,MANKEY,5,RHYHORN,5,MACHOP,0
BrockData:
	db $FF,5,GEODUDE,5,RHYHORN,0
MistyData:
	db $FF,5,STARYU,5,STARYU,0
LtSurgeData:
	db $FF,5,VOLTORB,5,PEKACHU,5,PEKACHU,0
ErikaData:
	db $FF,5,BELLSPROUT,5,BELLSPROUT,5,ODDISH,0
KogaData:
	db $FF,5,SMOGON,5,GRIMER,5,SMOGON,5,SMOGON,0
BlaineData:
	db $FF,5,GROWLITHE,5,PONYTA,5,PONYTA,5,GROWLITHE,0
SabrinaData:
	db $FF,5,ABRA,5,MR_MIME,5,VENONANT,5,ABRA,0
GentlemanData:
; SS Anne 1F Rooms
	db 5,GROWLITHE,GROWLITHE,0
	db 5,NIDORAN_M,NIDORAN_F,0
; SS Anne 2F Rooms/Vermilion Gym
	db 5,PEKACHU,0
; Unused
	db 5,MANKEY,0
; SS Anne 2F Rooms
	db 5,GROWLITHE,PONYTA,0
Green2Data:
; SS Anne 2F
	db $FF,5,PIDGEY,5,DODUO,5,SQUIRTLE,0
	db $FF,5,PIDGEY,5,DODUO,5,BULBASAUR,0
	db $FF,5,PIDGEY,5,DODUO,5,CHARMANDER,0
; Pokémon Tower 2F
	db $FF,5,GROWLITHE,5,EXEGGCUTE,5,SQUIRTLE,0
	db $FF,5,TENTACOOL,5,GROWLITHE,5,BULBASAUR,0
	db $FF,5,EXEGGCUTE,5,TENTACOOL,5,CHARMANDER,0
; Silph Co. 7F
	db $FF,5,EXEGGCUTE,5,ABRA,5,SQUIRTLE,0
	db $FF,5,GROWLITHE,5,ABRA,5,BULBASAUR,0
	db $FF,5,TENTACOOL,5,ABRA,5,CHARMANDER,0
; Route 22
	db $FF,5,GROWLITHE,5,ABRA,5,SQUIRTLE,0
	db $FF,5,TENTACOOL,5,GROWLITHE,5,BULBASAUR,0
	db $FF,5,RHYHORN,5,TENTACOOL,5,CHARMANDER,0
Green3Data:
	db $FF,5,GROWLITHE,5,EXEGGCUTE,5,SQUIRTLE,0
	db $FF,5,TENTACOOL,5,GROWLITHE,5,BULBASAUR,0
	db $FF,5,EXEGGCUTE,5,TENTACOOL,5,CHARMANDER,0
LoreleiData:
	db $FF,5,SEEL,5,SHELLDER,5,SLOWPOKE,0
ChannelerData:
; Unused
	db 5,GASTLY,0
	db 5,GASTLY,0
	db 5,GASTLY,GASTLY,0
	db 5,GASTLY,0
; Pokémon Tower 3F
	db 5,GASTLY,0
	db 5,GASTLY,0
; Unused
	db 5,GASTLY,0
; Pokémon Tower 3F
	db 5,GASTLY,0
; Pokémon Tower 4F
	db 5,GASTLY,0
	db 5,GASTLY,GASTLY,0
; Unused
	db 5,GASTLY,0
; Pokémon Tower 4F
	db 5,GASTLY,0
; Unused
	db 5,GASTLY,0
; Pokémon Tower 5F
	db 5,GASTLY,0
; Unused
	db 5,GASTLY,0
; Pokémon Tower 5F
	db 5,GASTLY,0
	db 5,GASTLY,0
	db 5,GASTLY,0
; Pokémon Tower 6F
	db 5,GASTLY,GASTLY,GASTLY,0
	db 5,GASTLY,0
	db 5,GASTLY,0
; Saffron Gym
	db 5,GASTLY,GASTLY,0
	db 5,GASTLY,0
	db 5,GASTLY,GASTLY,GASTLY,0
AgathaData:
	db $FF,5,GASTLY,5,ERKANS,5,GASTLY,0
LanceData:
	db $FF,5,DRATINI,5,DRATINI,5,DRATINI,0
